version: "3.4"

services:
  emotext:
    build: .
    image: emotext
    container_name: emotext
    environment:
      DATABASE_URL: "ecto://emotext:emotext@db/emotext"
      PHX_HOST: emotext.micrantha.test
      PORT: "80"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE:?set SECRET_KEY_BASE}"
      GUARDIAN_SECRET_KEY: "${GUARDIAN_SECRET_KEY:?set GUARDIAN_SECRET_KEY}"
    ports:
      - "1337:80"
    networks:
      - emotext
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: emotext
      POSTGRES_PASSWORD: emotext
      POSTGRES_DB: emotext
    #volumes:
    #  - ./scripts:/docker-entrypoint-initdb.d/
    networks:
      - emotext

networks:
  emotext: {}
