version: "3.4"

services:

  emotext:
    build: .
    image: emotext
    container_name: emotext
    environment:
      DATABASE_URL: "mongodb://mongo/emotext"
      HOST: "emotext.micrantha.com"
      SECRET_KEY_BASE: "c03feb4dd8371035041f2b7381f87b1ab6852da1b8842641dc8ab6f08df2692748543f1061ecbaf8b79f0fb9901cfd416cdc52162afadc52438d92693b53a81b"
    ports:
      - "1337:80"
    networks:
      - emotext

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_DATABASE: emotext
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
    networks:
      - emotext

networks:
  emotext: {}