import Config

config :emotext, Emotext.Repo,
  url: System.get_env("DATABASE_URL"),
  pool_size: 20 # The amount of database connections in the pool

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :tmp, TmpWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Tmp.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.


# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
#config :emotext, Emotext.Endpoint,
#  http: [port: System.get_env("PORT") || 80],
#  url: [host: System.get_env("HOST") || "emotext.micrantha.com"],
#  server: true,
#  root: ".",
#  version: Mix.Project.config[:version],
#  #force_ssl: [rewrite_on: [:x_forwarded_proto]],
#  secret_key_base: System.get_env("SECRET_KEY_BASE") || "c03feb4dd8371035041f2b7381f87b1ab6852da1b8842641dc8ab6f08df2692748543f1061ecbaf8b79f0fb9901cfd416cdc52162afadc52438d92693b53a81b",
#  cache_static_manifest: "priv/static/manifest.json"

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section, and set your `:url` port to 443
#
#  config :emotext, Emotext.Endpoint,
#    ...
#    url: [host: "example.com", port: 443],
#    https: [port: 443,
#            keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#            certfile: System.get_env("SOME_APP_SSL_CERT_PATH")]
#
# Where those two env variables point to a file on
# disk for the key and cert.

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
#     config :phoenix, :serve_endpoints, true
#
# Alternatively, you can configure exactly which server to
# start per endpoint:
#
#     config :emotext, Emotext.Endpoint, server: true
#
