db.aliases.insert({ "name": ":-)", action_id: db.actions.findOne({ name: "smile" }, { _id: 1})._id })

db.aliases.insert({ "name": ":-)", action_id: db.actions.findOne({ name: "smile" }, { _id: 1})._id })
db.aliases.insert({ "name": ":)", action_id: db.actions.findOne({ name: "smile" }, { _id: 1})._id })
db.aliases.insert({ "name": ":D", action_id: db.actions.findOne({ name: "smile" }, { _id: 1})._id })
db.aliases.insert({ "name": ":o)", action_id: db.actions.findOne({ name: "smile" }, { _id: 1})._id })
db.aliases.insert({ "name": ":]", action_id: db.actions.findOne({ name: "smile" }, { _id: 1})._id })
db.aliases.insert({ "name": ":3", action_id: db.actions.findOne({ name: "smile" }, { _id: 1})._id })
db.aliases.insert({ "name": ":c)", action_id: db.actions.findOne({ name: "smile" }, { _id: 1})._id })
db.aliases.insert({ "name": ":>", action_id: db.actions.findOne({ name: "smile" }, { _id: 1})._id })
db.aliases.insert({ "name": "=]", action_id: db.actions.findOne({ name: "smile" }, { _id: 1})._id })
db.aliases.insert({ "name": "8)", action_id: db.actions.findOne({ name: "smile" }, { _id: 1})._id })
db.aliases.insert({ "name": "=)", action_id: db.actions.findOne({ name: "smile" }, { _id: 1})._id })
db.aliases.insert({ "name": ":}", action_id: db.actions.findOne({ name: "smile" }, { _id: 1})._id })
db.aliases.insert({ "name": ":^)", action_id: db.actions.findOne({ name: "smile" }, { _id: 1})._id })
db.aliases.insert({ "name": ":っ)", action_id: db.actions.findOne({ name: "smile" }, { _id: 1})._id })


db.aliases.insert({ "name": ":-D", action_id: db.actions.findOne({ name: "laugh" }, { _id: 1})._id })
db.aliases.insert({ "name": "8-D", action_id: db.actions.findOne({ name: "laugh" }, { _id: 1})._id })
db.aliases.insert({ "name": "8D", action_id: db.actions.findOne({ name: "laugh" }, { _id: 1})._id })
db.aliases.insert({ "name": "x-D", action_id: db.actions.findOne({ name: "laugh" }, { _id: 1})._id })
db.aliases.insert({ "name": "xD", action_id: db.actions.findOne({ name: "laugh" }, { _id: 1})._id })
db.aliases.insert({ "name": "X-D", action_id: db.actions.findOne({ name: "laugh" }, { _id: 1})._id })
db.aliases.insert({ "name": "XD", action_id: db.actions.findOne({ name: "laugh" }, { _id: 1})._id })
db.aliases.insert({ "name": "=-D", action_id: db.actions.findOne({ name: "laugh" }, { _id: 1})._id })
db.aliases.insert({ "name": "=D", action_id: db.actions.findOne({ name: "laugh" }, { _id: 1})._id })
db.aliases.insert({ "name": "=-3", action_id: db.actions.findOne({ name: "laugh" }, { _id: 1})._id })
db.aliases.insert({ "name": "=3", action_id: db.actions.findOne({ name: "laugh" }, { _id: 1})._id })
db.aliases.insert({ "name": "B^D", action_id: db.actions.findOne({ name: "laugh" }, { _id: 1})._id })

db.aliases.insert({ "name": ":-))", action_id: db.actions.findOne({ name: "beam" }, { _id: 1})._id })

db.aliases.insert({ "name": ">:[", action_id: db.actions.findOne({ name: "frown" }, { _id: 1})._id })
db.aliases.insert({ "name": ":-(", action_id: db.actions.findOne({ name: "frown" }, { _id: 1})._id })
db.aliases.insert({ "name": ":(", action_id: db.actions.findOne({ name: "frown" }, { _id: 1})._id })
db.aliases.insert({ "name": ":-c", action_id: db.actions.findOne({ name: "frown" }, { _id: 1})._id })
db.aliases.insert({ "name": ":c", action_id: db.actions.findOne({ name: "frown" }, { _id: 1})._id })
db.aliases.insert({ "name": ":-<", action_id: db.actions.findOne({ name: "frown" }, { _id: 1})._id })
db.aliases.insert({ "name": ":っC", action_id: db.actions.findOne({ name: "frown" }, { _id: 1})._id })
db.aliases.insert({ "name": ":<", action_id: db.actions.findOne({ name: "frown" }, { _id: 1})._id })
db.aliases.insert({ "name": ":-[", action_id: db.actions.findOne({ name: "frown" }, { _id: 1})._id })
db.aliases.insert({ "name": ":[", action_id: db.actions.findOne({ name: "frown" }, { _id: 1})._id })
db.aliases.insert({ "name": ":{", action_id: db.actions.findOne({ name: "frown" }, { _id: 1})._id })


db.aliases.insert({ "name": ":-||", action_id: db.actions.findOne({ name: "fume" }, { _id: 1})._id })
db.aliases.insert({ "name": ":@", action_id: db.actions.findOne({ name: "fume" }, { _id: 1})._id })
db.aliases.insert({ "name": ">:(", action_id: db.actions.findOne({ name: "fume" }, { _id: 1})._id })

db.aliases.insert({ "name": ";-)", action_id: db.actions.findOne({ name: "wink" }, { _id: 1})._id })
db.aliases.insert({ "name": ";)", action_id: db.actions.findOne({ name: "wink" }, { _id: 1})._id })
db.aliases.insert({ "name": "*-)", action_id: db.actions.findOne({ name: "wink" }, { _id: 1})._id })
db.aliases.insert({ "name": "*)", action_id: db.actions.findOne({ name: "wink" }, { _id: 1})._id })
db.aliases.insert({ "name": ";-]", action_id: db.actions.findOne({ name: "wink" }, { _id: 1})._id })
db.aliases.insert({ "name": ";]", action_id: db.actions.findOne({ name: "wink" }, { _id: 1})._id })
db.aliases.insert({ "name": ";D", action_id: db.actions.findOne({ name: "wink" }, { _id: 1})._id })
db.aliases.insert({ "name": ";^)", action_id: db.actions.findOne({ name: "wink" }, { _id: 1})._id })
db.aliases.insert({ "name": ":-,", action_id: db.actions.findOne({ name: "wink" }, { _id: 1})._id })


db.aliases.insert({ "name": ">:P", action_id: db.actions.findOne({ name: "raspberry" }, { _id: 1})._id })
db.aliases.insert({ "name": ":-P", action_id: db.actions.findOne({ name: "raspberry" }, { _id: 1})._id })
db.aliases.insert({ "name": ":P", action_id: db.actions.findOne({ name: "raspberry" }, { _id: 1})._id })
db.aliases.insert({ "name": "X-P", action_id: db.actions.findOne({ name: "raspberry" }, { _id: 1})._id })
db.aliases.insert({ "name": "x-p", action_id: db.actions.findOne({ name: "raspberry" }, { _id: 1})._id })
db.aliases.insert({ "name": "xp", action_id: db.actions.findOne({ name: "raspberry" }, { _id: 1})._id })
db.aliases.insert({ "name": "XP", action_id: db.actions.findOne({ name: "raspberry" }, { _id: 1})._id })
db.aliases.insert({ "name": ":-p", action_id: db.actions.findOne({ name: "raspberry" }, { _id: 1})._id })
db.aliases.insert({ "name": ":p", action_id: db.actions.findOne({ name: "raspberry" }, { _id: 1})._id })
db.aliases.insert({ "name": "=p", action_id: db.actions.findOne({ name: "raspberry" }, { _id: 1})._id })
db.aliases.insert({ "name": ":-Þ", action_id: db.actions.findOne({ name: "raspberry" }, { _id: 1})._id })
db.aliases.insert({ "name": ":Þ", action_id: db.actions.findOne({ name: "raspberry" }, { _id: 1})._id })
db.aliases.insert({ "name": ":þ", action_id: db.actions.findOne({ name: "raspberry" }, { _id: 1})._id })
db.aliases.insert({ "name": ":-þ", action_id: db.actions.findOne({ name: "raspberry" }, { _id: 1})._id })
db.aliases.insert({ "name": ":-b", action_id: db.actions.findOne({ name: "raspberry" }, { _id: 1})._id })
db.aliases.insert({ "name": ":b", action_id: db.actions.findOne({ name: "raspberry" }, { _id: 1})._id })
db.aliases.insert({ "name": "d:", action_id: db.actions.findOne({ name: "raspberry" }, { _id: 1})._id })

db.aliases.insert({ "name": ":$", action_id: db.actions.findOne({ name: "blush" }, { _id: 1})._id })

db.aliases.insert({ "name": "O:-)", action_id: db.actions.findOne({ name: "innocent" }, { _id: 1})._id })

db.aliases.insert({ "name": "o/\o", action_id: db.actions.findOne({ name: "highfive" }, { _id: 1})._id })
db.aliases.insert({ "name": "^5", action_id: db.actions.findOne({ name: "highfive" }, { _id: 1})._id })
db.aliases.insert({ "name": ">_>^", action_id: db.actions.findOne({ name: "highfive" }, { _id: 1})._id })
db.aliases.insert({ "name": "^<_<", action_id: db.actions.findOne({ name: "highfive" }, { _id: 1})._id })

db.aliases.insert({ "name": "\o/", action_id: db.actions.findOne({ name: "cheer" }, { _id: 1})._id })

db.aliases.insert({ "name": "@}-;-''---", action_id: db.actions.findOne({ name: "rose" }, { _id: 1})._id })
db.aliases.insert({ "name": "@>-->--", action_id: db.actions.findOne({ name: "rose" }, { _id: 1})._id })

db.aliases.insert({ "name": "\o/", action_id: db.actions.findOne({ name: "cheer" }, { _id: 1})._id })
